### ISSUE TITLE
Cask is not working

### ISSUE THREAD

**Issue by laulaz** [asio/homebrew-popcorn-time#2]
I get this error :

> Warning: Calling "cask :v1 => 'token'" is deprecated!
> Use "cask 'token'" instead.
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
> 
> Error: Download failed on Cask 'popcorn-time' with message: Download failed: http://188.166.17.42/build/Popcorn-Time-0.3.8-0-Mac.dmg
> 
> Error: nothing to install
>

**Comment by holms** [comment]
I declare this project officially dead 🗡
